services:
  db:
    image: postgres:latest
    init: true
    expose:
      - "5432"
    # This works, when connecting from host:
    #    ports:
    #      - 127.0.0.1:5432:5432
    volumes:
      - nextcloud_aio_database:/var/lib/postgresql/data:rw
      - nextcloud_aio_database_dump:/mnt/data:rw
    environment:
      - POSTGRES_PASSWORD=secretabcdef
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    networks:
      - db-network
  client:
    image: postgres:latest
    command:
      - 'bash'
      - '-c'
      - >
        "'
        while true;
        do 
          sleep 1;
        done
        '"
    volumes:
      - nextcloud_aio_database:/var/lib/postgresql/data:rw
      - nextcloud_aio_database_dump:/mnt/data:rw
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secretabcdef
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - 'PG_TEST_CMD=psql -d "postgresql://postgres:secretabcdef@db:5432/postgres" -c "select now()"'
    networks:
      - db-network
  debug-tools:
    image: pnnlmiscscripts/debug-toolbox:latest
    command:
      - 'bash'
      - '-c'
      - >
        "'
        while true;
        do 
          sleep 1;
        done
        '"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secretabcdef
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - 'PG_TEST_CMD=psql -d "postgresql://postgres:secretabcdef@db:5432/postgres" -c "select now()"'
    networks:
      - db-network
networks:
  db-network: